import "./globals.css";
import Header from "@/components/header/Header";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="h-[30vh] text-center text flex items-center justify-center flex-wrap py-[8vh] bg-zinc-100">
          <div className="text-5xl w-[100vw]">Crowd Wave</div>
          <div className="text-slate-400 ">
            Discover and fund the best campaigns. Make a difference today.
          </div>
        </div>

        {children}
      </body>
    </html>
  );
}
